### ISSUE TITLE
How can setup questionnaire

### ISSUE THREAD

**Issue by bretbas** [TgBotFramework/TgBotFramework#2]
Hello, can you explain me how to create and setup questionnaire?
Is it possible to do it with pipeline?

**Comment by Fedorus** [comment]
Hi, for that we have state/stage conception. 

https://github.com/TgBotFramework/TgBotFramework.Examples/tree/master/StageExample

Idea is:
You have 5 questions. Once user texts you - send him question and increase his state value by 1. 
Next time he sends you anything you'll have this state value and know that its probably answer to your question, then increase his state and send him next questions
Repeat until you have questions. 
For demo you can use https://github.com/TgBotFramework/TgBotFramework.Stages
For something more complex then questioner you may want to implement some parts of it on your own. 
(for example now state variable stored only in memory database, but its relatively easy to replace it with any relational DB and that will make your bot "stateless" and don't rely on application running all the time)

**Comment by bretbas** [comment]
I am looking for Lib that will not have infrastructure code in the handlers, like this context.UserStage.Step++
The entire questionnaire should be declaratively described in one place

**Comment by Fedorus** [comment]
You can do that yourself, for framework that's corner case. Plus any way you need a place to store the data )

**Comment by bretbas** [comment]
I do not have so much time to implement such a case. I am looking for solutions. I thought that your pipeline is the implementation of the questionnaire. Sorry

**Comment by Fedorus** [comment]
It's one of the way's but still needs some coding )
